### ISSUE TITLE
Functionality limited dialog box 

### ISSUE THREAD

**Issue by yossefEl** [umair13adil/simple_beacons_flutter#34]
First of all thanks a lot for making this plugin and share it with the community!

Can anyone tell me how to remove this dialog .. 

![Screenshot_2020-12-10-17-58-51-117_app.myUIR.Android.jpg](https://user-images.githubusercontent.com/39236784/101809040-5ddd4180-3b17-11eb-90c8-44a8a3f52a80.jpg)

**Comment by umair13adil** [comment]
@yossefEl This issue is identified in **v1.0.18.** I am working on its fix. A fix will be released today for this.

**Comment by yossefEl** [comment]
Thank you so much @umair13adil

**Comment by umair13adil** [comment]
@yossefEl New plugin version v1.0.19 is released, in that this issue is fixed:

```
    if (Platform.isAndroid) {
    
      //Prominent disclosure
      await BeaconsPlugin.setDisclosureDialogMessage(
          title: "Need Location Permission",
          message: "This app collects location data to work with beacons.");

      //Only in case, you want the dialog to be shown again. By Default, a dialog will never be shown if permissions are granted.
      await BeaconsPlugin.clearDisclosureDialogShowFlag(false);
    }
```

**Comment by mingjunsiek** [comment]
@umair13adil Is there anyway to not have this disclosure message at all? It is still showing up on the latest version.

**Comment by umair13adil** [comment]
@mingjunsiek 
To do that call this on init:

   await BeaconsPlugin.clearDisclosureDialogShowFlag(true);
